// data.jsx, MOCK. Anchored to real MYND figures where they exist so DB recognizes
// his own business. Everything else is shaped to demonstrate the surface.

const D = {
  meta: { user: "Damon B.", role: "Founder / CEO", tz: "Los Angeles", updated: "11:42 PM" },

  ticker: [
    { i: "dollar", l: "Revenue today", v: "$1,847" },
    { i: "box",    l: "Orders today", v: "14" },
    { i: "pulse",  l: "Approval rate", v: "94.75%", tone: "warn" },
    { i: "dollar", l: "Cash", v: "$40,347" },
    { i: "alert",  l: "Dubai Chocolate", v: "8d cover", tone: "bad" },
    { i: "rev",    l: "Rebill rate", v: "74%", tone: "good" },
    { i: "clock",  l: "Next buyout", v: "$9,481 · Oct 1" },
    { i: "truck",  l: "Shipments today", v: "11" },
    { i: "dollar", l: "MTD revenue", v: "$26,528" },
    { i: "pulse",  l: "Chargebacks 30d", v: "0.42%", tone: "good" },
  ],

  // ---------------------------------------------------------------- BOARDROOM
  unit: [
    { k:"rev",   label:"Revenue · 30d",   value:"$46,814", delta:-4.1, sub:"all four rails", tone:"ink", help:"Gross across every processor, matched to the bank.", spark:[64267,58900,55400,51200,49800,47300,45100,43900,46814] },
    { k:"cm",    label:"Contribution margin", value:"$29,247", delta:8.4, sub:"62.5% of revenue", tone:"good", help:"Revenue less cost of delivery and marketing. Fixed costs excluded. The number the business should orbit daily.", spark:[21400,19800,17900,16200,14840,28600,31200] },
    { k:"cash",  label:"Available cash",  value:"$40,347", delta:-37.2, sub:"floor $22,500", tone:"warn", help:"Across Mercury and BlueBanc. Free cash is what sits above the operating floor." },
    { k:"burn",  label:"Operating profit · 30d", value:"+$15,197", delta:3826, sub:"was +$387 in July", tone:"good", help:"Revenue less cost of delivery, marketing and fixed operating cost. Before debt service and owner distributions. Operating profit, not net profit." },
    { k:"amer",  label:"aMER",            value:"1.92x", delta:3.1, sub:"new cust rev / spend", tone:"good", help:"Acquisition MER. New customer revenue divided by ad spend. Blended and unattributed." },
    { k:"ncac",  label:"Cost per new customer", value:"$36.42", delta:-4.2, sub:"blended nCAC", tone:"warn", help:"Ad spend divided by new customer orders." },
    { k:"appr",  label:"Approval rate",   value:"94.75%", delta:0, sub:"target 98%", tone:"warn", help:"Three points below target is about $18,000 a year." },
    { k:"debt",  label:"Total owed",      value:"$176,859", delta:-15.7, sub:"next $9,481 Oct 1", tone:"ink", help:"Buyout note, card and the undated second obligation." },
  ],

  funnel: [
    { label:"Sessions",       v:18420, pct:100, note:"30 days" },
    { label:"Add to cart",    v:2210,  pct:62,  note:"12.0% of sessions" },
    { label:"Checkout",       v:418,   pct:34,  note:"18.9% of carts" },
    { label:"Paid order",     v:223,   pct:22,  note:"53.3% of checkouts" },
    { label:"Subscription",   v:30,    pct:9,   note:"13.4% attach" },
    { label:"Rebilled 3x",    v:3,     pct:3,   note:"10.98% survive" },
  ],

  today: [
    { l:"Orders today",     v:"14" },
    { l:"Revenue today",    v:"$1,847" },
    { l:"Shipments out",    v:"11" },
    { l:"Declines today",   v:"3", tone:"warn" },
    { l:"Support tickets",  v:"6" },
    { l:"Subs canceled",   v:"2", tone:"bad" },
  ],
  thisMonth: [
    { l:"Revenue",          v:"$26,528" },
    { l:"Operating profit", v:"$8,630", tone:"good" },
    { l:"Orders",           v:"126" },
    { l:"New subscribers",  v:"17" },
    { l:"Debt paid",        v:"$11,556", tone:"good" },
    { l:"Distributions",    v:"$0" },
  ],

  attention: [
    { t:"Dubai Chocolate runs out in 8 days against a 21 day lead time", tone:"bad" },
    { t:"Micro Caps has been at zero stock for 34 days", tone:"bad" },
    { t:"Three data sources still unconnected, so channel numbers are directional only", tone:"warn" },
    { t:"Card utilization at 49%. The Q4 plan would take it to 93%", tone:"warn" },
    { t:"Six of ten products still priced against a placeholder cost", tone:"warn" },
    { t:"Kitchen has logged 0 of 30 production runs", tone:"warn" },
  ],

  // ---------------------------------------------------------------- MONEY
  accounts: [
    { n:"Mercury · Operating", c:"1000", v:22500, role:"Holds the floor, spills to sweep", tone:"accent" },
    { n:"Mercury · Sweep",     c:"1010", v:0,     role:"Distributes to buckets", tone:"info" },
    { n:"Mercury · Marketing", c:"1040", v:0,     role:"35% of sweep", tone:"violet" },
    { n:"Mercury · Inventory", c:"1030", v:0,     role:"25% of sweep", tone:"good" },
    { n:"Mercury · Taxes",     c:"1050", v:0,     role:"20% of sweep", tone:"warn" },
    { n:"Mercury · Owner",     c:"1070", v:0,     role:"15% of sweep", tone:"accent" },
    { n:"Mercury · Reserve",   c:"1020", v:0,     role:"5%, caps at $108,000", tone:"mute" },
    { n:"Mercury · Debt svc",  c:"1060", v:6273,  role:"Funds the buyout schedule", tone:"bad" },
    { n:"BlueBanc · Settlement", c:"1080", v:34074, role:"Rails land here, sweeps to Mercury", tone:"info" },
  ],
  cashTrail: [
    { m:"Mar", v:98621 },{ m:"Apr", v:64317 },{ m:"May", v:65504 },
    { m:"Jun", v:82956 },{ m:"Jul", v:59962 },{ m:"Aug", v:56730 },{ m:"Sep", v:40347 },
  ],
  buckets: [
    { n:"Marketing", pct:35, target:13125, v:0, tone:"violet" },
    { n:"Inventory", pct:25, target:9375,  v:0, tone:"good" },
    { n:"Taxes",     pct:20, target:7500,  v:0, tone:"warn" },
    { n:"Owner profit", pct:15, target:5625, v:0, tone:"accent" },
    { n:"Reserve",   pct:5,  target:1875,  v:0, tone:"info" },
  ],
  pl: [
    { line:"Revenue",          v:46814, pct:100,  tone:"ink",  bench:"" },
    { line:"Cost of delivery", v:17567, pct:37.5, tone:"good", bench:"~40%", d:"Product cost, fulfillment, processing" },
    { line:"Marketing",        v:0,     pct:0,    tone:"warn", bench:"25-30%", d:"Ad spend paused" },
    { line:"Contribution margin", v:29247, pct:62.5, tone:"good", bench:"", d:"Revenue less cost of delivery and marketing", sub:true },
    { line:"OPEX",             v:14050, pct:30.0, tone:"bad",  bench:"~15%", d:"Fixed operating cost" },
    { line:"Operating profit", v:15197, pct:32.5, tone:"good", bench:"15-20%", d:"Contribution margin less OPEX. Before debt service and distributions", sub:true },
  ],
  debt: [
    { n:"Buyout note", v:73778, note:"8 of 9 payments left", payoff:"May 1, 2027", tone:"bad" },
    { n:"Chase card",  v:23081,  note:"$46,700 limit · 49% used · $2,600 a month from the debt bucket", payoff:"Jun 15, 2027", tone:"warn" },
    { n:"Second obligation", v:80000, note:"Undated, no written terms", payoff:"No date set", tone:"mute" },
  ],
  // combined buyout and card balance at each month end, on the schedule and the card plan
  payoffPath: [
    { m:"Sep", v:96859 },{ m:"Oct", v:84777 },{ m:"Nov", v:72770 },{ m:"Dec", v:60837 },{ m:"Jan", v:48977 },
    { m:"Feb", v:37192 },{ m:"Mar", v:25481 },{ m:"Apr", v:13844 },{ m:"May", v:2281 },{ m:"Jun", v:0 },
  ],
  schedule: [
    { d:"Sep 1, 2026", v:11555.56, s:"paid" },{ d:"Oct 1, 2026", v:9481.48, s:"next" },
    { d:"Nov 1, 2026", v:9407.41, s:"planned" },{ d:"Dec 1, 2026", v:9333.34, s:"planned" },
    { d:"Jan 1, 2027", v:9259.26, s:"planned" },{ d:"Feb 1, 2027", v:9185.19, s:"planned" },
    { d:"Mar 1, 2027", v:9111.11, s:"planned" },{ d:"Apr 1, 2027", v:9037.04, s:"planned" },
    { d:"May 1, 2027", v:8962.94, s:"planned" },
  ],
  rails: [
    { n:"Deposyt",    gross:19840, fees:874, res:0,   net:18966, pct:4.41, appr:96.2, cb:0.31, cap:60000, tone:"good" },
    { n:"ExpiTrans",  gross:14320, fees:648, res:0,   net:13672, pct:4.53, appr:94.1, cb:0.44, cap:40000, tone:"good" },
    { n:"Kurv / EMS", gross:7952,  fees:366, res:795, net:6791,  pct:4.60, appr:91.8, cb:0.67, cap:25000, tone:"warn" },
    { n:"Retired rail", gross:0,   fees:0,   res:500, net:0,     pct:0,    appr:0,    cb:0,    cap:0,     tone:"mute" },
  ],

  // Daily contribution margin, Aug 19 to Sep 17. Sums tie to the P&L: 30 days = $46,814 revenue,
  // $17,567 cost of delivery. September to date = $26,528. Sep 17 is today, matching revenue today.
  cmDaily: [
    { d:"Aug 19", w:"Wed", m:8, rev:1620, cod:608, mkt:0 },
    { d:"Aug 20", w:"Thu", m:8, rev:1650, cod:634, mkt:0 },
    { d:"Aug 21", w:"Fri", m:8, rev:1487, cod:540, mkt:0 },
    { d:"Aug 22", w:"Sat", m:8, rev:1351, cod:523, mkt:0 },
    { d:"Aug 23", w:"Sun", m:8, rev:1522, cod:575, mkt:0 },
    { d:"Aug 24", w:"Mon", m:8, rev:1732, cod:631, mkt:0 },
    { d:"Aug 25", w:"Tue", m:8, rev:1614, cod:624, mkt:0 },
    { d:"Aug 26", w:"Wed", m:8, rev:1561, cod:578, mkt:0 },
    { d:"Aug 27", w:"Thu", m:8, rev:1638, cod:606, mkt:0 },
    { d:"Aug 28", w:"Fri", m:8, rev:1546, cod:598, mkt:0 },
    { d:"Aug 29", w:"Sat", m:8, rev:1348, cod:492, mkt:0 },
    { d:"Aug 30", w:"Sun", m:8, rev:1465, cod:552, mkt:0 },
    { d:"Aug 31", w:"Mon", m:8, rev:1752, cod:670, mkt:0 },
    { d:"Sep 1", w:"Tue", m:9, rev:1650, cod:599, mkt:0 },
    { d:"Sep 2", w:"Wed", m:9, rev:1684, cod:646, mkt:0 },
    { d:"Sep 3", w:"Thu", m:9, rev:1503, cod:565, mkt:0 },
    { d:"Sep 4", w:"Fri", m:9, rev:1398, cod:511, mkt:0 },
    { d:"Sep 5", w:"Sat", m:9, rev:1444, cod:559, mkt:0 },
    { d:"Sep 6", w:"Sun", m:9, rev:1518, cod:560, mkt:0 },
    { d:"Sep 7", w:"Mon", m:9, rev:1552, cod:577, mkt:0 },
    { d:"Sep 8", w:"Tue", m:9, rev:1590, cod:613, mkt:0 },
    { d:"Sep 9", w:"Wed", m:9, rev:1671, cod:608, mkt:0 },
    { d:"Sep 10", w:"Thu", m:9, rev:1563, cod:592, mkt:0 },
    { d:"Sep 11", w:"Fri", m:9, rev:1395, cod:531, mkt:0 },
    { d:"Sep 12", w:"Sat", m:9, rev:1389, cod:505, mkt:0 },
    { d:"Sep 13", w:"Sun", m:9, rev:1536, cod:591, mkt:0 },
    { d:"Sep 14", w:"Mon", m:9, rev:1610, cod:602, mkt:0 },
    { d:"Sep 15", w:"Tue", m:9, rev:1555, cod:571, mkt:0 },
    { d:"Sep 16", w:"Wed", m:9, rev:1623, cod:628, mkt:0 },
    { d:"Sep 17", w:"Thu", m:9, rev:1847, cod:678, mkt:0 },
  ],
  // Owner distributions by month. Irregular draws before the Sep 15 cut-over.
  distributions: [
    { m:"Jan", v:4000 },{ m:"Feb", v:3500 },{ m:"Mar", v:6000 },{ m:"Apr", v:2500 },{ m:"May", v:0 },
    { m:"Jun", v:3000 },{ m:"Jul", v:0 },{ m:"Aug", v:1500 },{ m:"Sep", v:0 },
  ],
  // ---------------------------------------------------------------- REVENUE
  revMonthly: [
    { m:"Nov", v:64267 },{ m:"Dec", v:58900 },{ m:"Jan", v:55400 },{ m:"Feb", v:51200 },
    { m:"Mar", v:49800 },{ m:"Apr", v:47300 },{ m:"May", v:45100 },{ m:"Jun", v:43900 },{ m:"Jul", v:42112 },
  ],
  channels: [
    { m:"Organic / direct", v:18420, trust:"good" },
    { m:"Email",            v:6890,  trust:"low" },
    { m:"Wholesale",        v:4120,  trust:"mock" },
    { m:"Creators",         v:400,   trust:"low" },
    { m:"Paid social",      v:0,     trust:"good" },
    { m:"Unattributed",     v:12282, trust:"none", tone:"bad" },
  ],
  products: [
    { sku:"Dubai Chocolate",          cat:"Chocolate", price:69, cost:6.72, basis:"measured", margin:90.3, units:142, rev:9798, trend:[118,126,131,138,142] },
    { sku:"Sea Salt Chocolate",       cat:"Chocolate", price:69, cost:6.26, basis:"measured", margin:90.9, units:105, rev:7245, trend:[96,99,103,101,105] },
    { sku:"Strawberry Mango Gummies", cat:"Gummies",   price:69, cost:10.00, basis:"placeholder", margin:null, units:94, rev:6486, trend:[71,78,84,90,94] },
    { sku:"Matcha Chocolate",         cat:"Chocolate", price:69, cost:7.25, basis:"measured", margin:89.5, units:80, rev:5520, trend:[92,88,85,82,80] },
    { sku:"Blue Raspberry Gummies",   cat:"Gummies",   price:69, cost:10.00, basis:"placeholder", margin:null, units:77, rev:5313, trend:[58,64,69,74,77] },
    { sku:"Mint Chocolate",           cat:"Chocolate", price:69, cost:6.91, basis:"measured", margin:90.0, units:62, rev:4278, trend:[68,66,64,63,62] },
    { sku:"Toffee Chocolate",         cat:"Chocolate", price:69, cost:7.02, basis:"measured", margin:89.8, units:48, rev:3312, trend:[52,50,49,48,48] },
    { sku:"Espresso Chocolate",       cat:"Chocolate", price:69, cost:6.88, basis:"measured", margin:90.0, units:41, rev:2829, trend:[46,44,43,42,41] },
    { sku:"Micro Caps",               cat:"Capsules",  price:null, cost:10.00, basis:"placeholder", margin:null, units:0, rev:0, trend:[0,0,0,0,0] },
  ],
  subs: {
    // Last 30 days against the 30 before. Active end = active start + new - cancellations.
    kpi: [
      { label:"Total active subs",  value:"1,842", delta:-3.2, tone:"warn", sub:"was 1,903 last month" },
      { label:"New subs started",   value:"30",    delta:7.1,  tone:"good", sub:"was 28" },
      { label:"Cancellations",      value:"91",    delta:8.3,  invert:true, tone:"bad", sub:"churn 4.8%, was 4.3%" },
      { label:"Net new subs",       value:"-61",   delta:-5, deltaUnit:"", tone:"bad", sub:"was -56. New less cancellations" },
      { label:"M1 retention",       value:"42%",   delta:2, deltaUnit:" pts", tone:"warn", sub:"still active after the first rebill" },
      { label:"M2 retention",       value:"21%",   delta:-1, deltaUnit:" pts", tone:"warn", sub:"after the second" },
      { label:"M3 retention",       value:"11.0%", delta:-0.4, deltaUnit:" pts", tone:"bad", sub:"after the third" },
      { label:"Rebill rate",        value:"74%",   delta:13, deltaUnit:" pts", tone:"good", sub:"was 61%" },
    ],
    months: [
      { m:"Apr", active:2186, neu:44, cancel:148, churn:6.5, net:-104, m1:38, m2:24, m3:14.0, rebill:71 },
      { m:"May", active:2097, neu:39, cancel:128, churn:5.9, net:-89,  m1:36, m2:23, m3:13.0, rebill:48 },
      { m:"Jun", active:2012, neu:35, cancel:120, churn:5.7, net:-85,  m1:35, m2:21, m3:12.0, rebill:33 },
      { m:"Jul", active:1959, neu:31, cancel:84,  churn:4.2, net:-53,  m1:39, m2:20, m3:11.6, rebill:27.3 },
      { m:"Aug", active:1903, neu:28, cancel:84,  churn:4.3, net:-56,  m1:40, m2:22, m3:11.4, rebill:61 },
      { m:"Last 30 days", active:1842, neu:30, cancel:91, churn:4.8, net:-61, m1:42, m2:21, m3:11.0, rebill:74 },
    ],
    rebill: [{m:"Feb",v:100},{m:"Mar",v:96},{m:"Apr",v:71},{m:"May",v:48},{m:"Jun",v:33},{m:"Jul",v:27.3},{m:"Aug",v:61},{m:"Sep",v:74}],
  },

  // ---------------------------------------------------------------- MARKETING
  ads: {
    kpi: [
      { label:"Blended ROAS", value:"-", sub:"no spend to measure", tone:"mute" },
      { label:"Ad spend · 30d", value:"$0", sub:"paused since August", tone:"mute" },
      { label:"CAC", value:"-", sub:"needs attribution", tone:"mute" },
      { label:"Impressions", value:"0", sub:"all channels", tone:"mute" },
      { label:"CTR", value:"0.00%", sub:"-", tone:"mute" },
      { label:"Planned Q4 budget", value:"$13,125", sub:"35% of sweep", tone:"violet" },
    ],
    accounts: [
      { n:"Meta Business", id:"act_8841203", status:"Paused", spend:0, imp:0, clicks:0, ctr:0, cpc:0, leads:0 },
      { n:"TikTok Ads",    id:"act_5520918", status:"Not connected", spend:0, imp:0, clicks:0, ctr:0, cpc:0, leads:0 },
      { n:"Google Ads",    id:"act_2290471", status:"Not connected", spend:0, imp:0, clicks:0, ctr:0, cpc:0, leads:0 },
    ],
    social: [
      { n:"Instagram", followers:"24.8K", growth:1.9, posts:12, eng:"3.4%", tone:"good" },
      { n:"TikTok",    followers:"11.2K", growth:6.4, posts:18, eng:"5.1%", tone:"good" },
      { n:"YouTube",   followers:"2.1K",  growth:0.4, posts:3,  eng:"1.8%", tone:"warn" },
      { n:"X",         followers:"1.4K",  growth:-0.7, posts:6, eng:"0.9%", tone:"bad" },
    ],
  },

  // ---------------------------------------------------------------- OPS
  inventory: [
    { sku:"Dubai Chocolate",          cat:"Chocolate", hand:980,  vel:117, cover:8,   lead:21, st:"critical", po:61000, inc:true },
    { sku:"Micro Caps",               cat:"Capsules",  hand:0,    vel:0,   cover:0,   lead:30, st:"critical", po:0, inc:false, note:"Never produced" },
    { sku:"Strawberry Mango Gummies", cat:"Gummies",   hand:2210, vel:104, cover:21,  lead:24, st:"warning",  po:142000, inc:true },
    { sku:"Sea Salt Chocolate",       cat:"Chocolate", hand:3100, vel:92,  cover:34,  lead:18, st:"warning",  po:53000, inc:true },
    { sku:"Mint Chocolate",           cat:"Chocolate", hand:5640, vel:83,  cover:68,  lead:18, st:"healthy",  po:0, inc:false },
    { sku:"Toffee Chocolate",         cat:"Chocolate", hand:3790, vel:57,  cover:66,  lead:18, st:"healthy",  po:0, inc:false },
    { sku:"Espresso Chocolate",       cat:"Chocolate", hand:4680, vel:46,  cover:102, lead:18, st:"healthy",  po:0, inc:false },
    { sku:"Blue Raspberry Gummies",   cat:"Gummies",   hand:4920, vel:63,  cover:78,  lead:24, st:"healthy",  po:0, inc:false },
    { sku:"Matcha Chocolate",         cat:"Chocolate", hand:8100, vel:39,  cover:208, lead:18, st:"over",     po:0, inc:false },
  ],
  production: {
    runs: [
      { d:"Pending", product:"Dubai Chocolate", input:"-", output:"-", yield:null, cost:null, st:"scheduled" },
      { d:"Aug 14", product:"Sea Salt Chocolate", input:"48 lb", output:"1,180 bars", yield:92.4, cost:6.26, st:"estimated" },
      { d:"Jul 22", product:"Mint Chocolate", input:"41 lb", output:"980 bars", yield:90.1, cost:6.91, st:"estimated" },
      { d:"Jul 03", product:"Matcha Chocolate", input:"38 lb", output:"860 bars", yield:88.2, cost:7.25, st:"estimated" },
    ],
    rates: [
      { l:"Labor", v:"$25 / hr" },{ l:"Kitchen rent", v:"$2,200 / mo" },
      { l:"Active ingredient", v:"$300 / lb" },{ l:"Delivery", v:"$150 / run" },
    ],
  },
  suppliers: [
    { n:"LA Manufacturer", what:"Gummies and capsules", terms:"100% up front", lead:"24 days", spend:142000, risk:"warn" },
    { n:"Own kitchen", what:"All chocolate", terms:"n/a", lead:"18-21 days", spend:26400, risk:"good" },
    { n:"Ingredient supplier", what:"Active ingredient", terms:"Retail, no account", lead:"7 days", spend:31200, risk:"bad" },
    { n:"Packaging", what:"Boxes, labels, inserts", terms:"Net 0", lead:"14 days", spend:14800, risk:"warn" },
    { n:"3PL warehouse", what:"Pick, pack, ship", terms:"Monthly invoice", lead:"n/a", spend:18900, risk:"good" },
  ],

  // ---------------------------------------------------------------- GOALS
  goals: [
    { g:"Monthly revenue", now:"$46.8K", target:"$85K", pct:55, tone:"warn", bench:70, note:"Back to the November run rate, then past it" },
    { g:"Fixed cost ratio", now:"30.0%", target:"15%", pct:50, tone:"bad", bench:100, note:"Benchmark for DTC is about 15% of revenue" },
    { g:"Contribution margin", now:"$29.2K", target:"$53K", pct:55, tone:"warn", bench:null, note:"62.5% of revenue. The target is the same margin on the $85K revenue goal" },
    { g:"Chargeback rate", now:"0.42%", target:"under 1%", pct:100, tone:"good", bench:null, note:"Across all rails, last 30 days. Rail C runs highest at 0.67%" },
    { g:"Rebill rate", now:"74%", target:"90%", pct:82, tone:"warn", bench:85, note:"Was 27.3% in July. Credentials restored" },
    { g:"Cycle-3 retention", now:"11.0%", target:"45%", pct:24, tone:"bad", bench:55, note:"The single weakest number in the business" },
    { g:"Days of cover, worst SKU", now:"8d", target:"45d", pct:18, tone:"bad", bench:60, note:"Anything under lead time is a stockout waiting" },
    { g:"Debt outstanding", now:"$177K", target:"$0", pct:38, tone:"warn", bench:50, note:"$33,000 paid down in the last month" },
  ],

  // ---------------------------------------------------------------- TEAM
  tasks: {
    cols: [
      { k:"blocked", l:"Blocked", tone:"bad", items:[
        { t:"Warehouse system access", who:"DB", p:"High" },
        { t:"Email platform access", who:"DB", p:"High" },
        { t:"Attribution history export", who:"DB", p:"High" },
      ]},
      { k:"queue", l:"Queue", tone:"mute", items:[
        { t:"Move ingredients to wholesale accounts", who:"DB", p:"Med" },
        { t:"Second card application", who:"DB", p:"Med" },
        { t:"Clinic pricing sheet", who:"Sales", p:"Low" },
        { t:"Retention offer copy", who:"Rebekka", p:"Med" },
      ]},
      { k:"doing", l:"In progress", tone:"accent", items:[
        { t:"First-order payment cascade", who:"Victor", p:"High" },
        { t:"Attribution rebuild, 30 day window", who:"Victor", p:"High" },
        { t:"Kitchen ledger rollout", who:"Jose", p:"High" },
        { t:"Product page rebuild", who:"Designer", p:"Med" },
      ]},
      { k:"done", l:"Done", tone:"good", items:[
        { t:"Card data exposure closed", who:"Victor", p:"High" },
        { t:"Security fix list cleared", who:"Victor", p:"High" },
        { t:"Cost base cut by $14,810/mo", who:"DB", p:"High" },
        { t:"Code moved to client ownership", who:"Victor", p:"Med" },
      ]},
    ],
  },
  vault: [
    { n:"Supplier agreements", c:6, tone:"accent", note:"Manufacturer, packaging, 3PL" },
    { n:"Bills of materials", c:8, tone:"violet", note:"Per supplier. Drives negotiation and charge review" },
    { n:"Processor agreements", c:4, tone:"warn", note:"Includes volume caps and reserve terms" },
    { n:"Entity and formation", c:9, tone:"bad", note:"Restricted" },
    { n:"Insurance", c:3, tone:"info", note:"Product liability, general" },
    { n:"Trademark and IP", c:5, tone:"violet", note:"Filed and pending" },
    { n:"Role documents", c:11, tone:"accent", note:"Nine role documents, metrics by role, role scorecards" },
    { n:"Lab reports and COAs", c:28, tone:"good", note:"Per batch, public facing" },
  ],
  drive: [
    { n:"Financial reconstruction", t:"Spreadsheet", d:"Sep 8", size:"2.4 MB" },
    { n:"Kitchen ledger", t:"Spreadsheet", d:"Aug 27", size:"180 KB" },
    { n:"Tech stack and vendors", t:"Spreadsheet", d:"Sep 2", size:"340 KB" },
    { n:"Build plan", t:"Document", d:"Aug 26", size:"1.1 MB" },
    { n:"Role scorecards", t:"Document", d:"Sep 18", size:"88 KB" },
    { n:"Metrics by role", t:"Document", d:"Sep 18", size:"112 KB" },
    { n:"Metrics tracker", t:"Spreadsheet", d:"Sep 18", size:"64 KB" },
    { n:"Roles and responsibilities", t:"Document", d:"Sep 2", size:"96 KB" },
    { n:"Brand assets", t:"Folder", d:"Jul 14", size:"142 MB" },
  ],
  agents: [
    { n:"Support agent", s:"planned", d:"Answers order status, shipping and refund questions from the order platform and the 3PL, escalating anything it can't resolve.", impact:"Halves support load" },
    { n:"Content agent", s:"planned", d:"Drafts product copy, email sequences and social posts against the brand voice and the claims policy.", impact:"Replaces a freelancer" },
    { n:"Inventory agent", s:"planned", d:"Watches days of cover per product and raises a purchase order before anything crosses its lead time.", impact:"Ends stockouts" },
    { n:"Reconciliation agent", s:"planned", d:"Matches processor settlements to bank deposits daily and flags anything that doesn't tie.", impact:"Removes manual close work" },
    { n:"Creator agent", s:"shelved", d:"Managed creator onboarding, link generation and payout calculation.", impact:"Program wound down" },
  ],
  dataHealth: [
    { n:"Mercury",        s:"live",    d:"Operating account and buckets" },
    { n:"BlueBanc",       s:"live",    d:"Settlement account" },
    { n:"Xero",           s:"live",    d:"78 accounts, all coded" },
    { n:"Order platform", s:"live",    d:"Orders, subscriptions, cascade" },
    { n:"Affiliate platform", s:"live", d:"Access received 24 August" },
    { n:"Chase card",     s:"partial", d:"Feed not connected" },
    { n:"Processors",     s:"partial", d:"Two of three self-serve" },
    { n:"Warehouse",      s:"blocked", d:"Access outstanding" },
    { n:"Email platform", s:"blocked", d:"Access outstanding" },
    { n:"Attribution history", s:"blocked", d:"Export outstanding" },
    { n:"Kitchen ledger", s:"waiting", d:"Built, waiting on first run" },
    { n:"Site analytics", s:"partial", d:"Being installed" },
  ],
  reliability: [
    { a:"Cash position",   l:"high",   n:"Reconstructed from bank and card statements" },
    { a:"Fixed costs",     l:"high",   n:"Verified line by line" },
    { a:"Debt schedule",   l:"high",   n:"From the signed agreement" },
    { a:"Revenue by rail", l:"medium", n:"Two of three portals self-serve" },
    { a:"Approval rates",  l:"medium", n:"Gateway reports, not re-measured" },
    { a:"Margin per unit", l:"low",    n:"Placeholder cost on six of ten products" },
    { a:"Inventory cover", l:"low",    n:"Needs warehouse access" },
    { a:"Channel revenue", l:"none",   n:"Attribution broken since April" },
    { a:"Lifetime value",  l:"none",   n:"Needs attribution first" },
  ],
};
