// data5.jsx, the team layer. Seats, scorecards and the weekly score log.
// Folded from the MYND role documents, Metrics by role, Role scorecards and
// the Metrics tracker, September 18, 2026. Every seat is scored on every
// metric it's held to, not just the primary one. Targets, cadence, sources and
// status logic match the Metrics tracker. Sample history is modeled.

const WEEKS = ["Sep 21","Sep 28","Oct 5","Oct 12","Oct 19","Oct 26","Nov 2","Nov 9","Nov 16","Nov 23","Nov 30",
  "Dec 7","Dec 14","Dec 21","Dec 28","Jan 4","Jan 11","Jan 18","Jan 25","Feb 1","Feb 8","Feb 15","Feb 22",
  "Mar 1","Mar 8","Mar 15"];

// Seat-level context. measure and need describe the primary number.
// unit on metrics: "n" count, "h" hours, "pct" percent, "usd" dollars, "rate" units per dollar, "yes" 1 or 0
const SEATS = [
  { id:"founder", seat:"Founder and Owner", short:"Founder", who:"DB", reports:null,
    line:"Set direction, hold the relationships only an owner can hold, and get out of the way of everything else.",
    manages:"Direction, money movement, processors, outside advisors",
    not:"The day to day. That's the COO.",
    measure:"Measurable", need:"Decision log, already running",
    doc:"09 Founder and Owner", },
  { id:"coo", seat:"Chief Operating Officer", short:"COO", who:"Camila", reports:"founder",
    line:"Run the day to day so the business works without the owner in the middle of every task.",
    manages:"Suppliers and manufacturers, the warehouse, day to day coordination",
    not:"Recipes, code or brand direction.",
    measure:"Needs 30 days", need:"History before a target means anything",
    doc:"01 Chief Operating Officer", },
  { id:"content", seat:"Content and Brand Lead", short:"Content and Brand", who:"Rebekka", reports:"founder",
    line:"Own the brand and make the outside teams work as one.",
    manages:"The email and SMS agency, the creator VA, brand review",
    not:"What gets built or when. Paid advertising.",
    measure:"Needs attribution", need:"Channel revenue, blocked until attribution is rebuilt",
    doc:"02 Content and Brand Lead", },
  { id:"dev", seat:"Developer", short:"Developer", who:"Victor", reports:"founder",
    line:"Ship the features that let customers do more for themselves and let the business earn more per customer.",
    manages:"The codebase and the three repositories",
    not:"Brand, copy or what the offer is. Takes work only from the owner.",
    measure:"Needs roadmap", need:"A written roadmap to ship against",
    doc:"03 Developer", },
  { id:"support", seat:"Customer Support", short:"Support", who:"S.J.", reports:"founder", moving:"coo",
    line:"Get customer problems resolved fast, and make sure nothing sits waiting.",
    manages:"The support inbox and every open customer issue",
    not:"Refund policy, pricing or anything that changes the offer.",
    measure:"Needs build", need:"Resolution timestamps out of the support tool",
    doc:"04 Customer Support", },
  { id:"wholesale", seat:"Wholesale and Clinic Sales", short:"Wholesale", who:"Clinic channel", reports:"founder",
    line:"Open and hold wholesale accounts, so revenue stops depending only on direct consumers.",
    manages:"The wholesale pipeline and every account in it",
    not:"Pricing, terms, or placing orders with the warehouse.",
    measure:"Measurable", need:"Activity log, already running",
    doc:"05 Wholesale and Clinic Sales", },
  { id:"kitchen", seat:"Kitchen and Production", short:"Kitchen", who:"Jose", reports:"founder", moving:"coo",
    line:"Make the product, on schedule, at a cost the business can measure.",
    manages:"The kitchen, the production schedule, ingredient ordering for a run",
    not:"What gets made or how much. That comes from the reorder plan.",
    measure:"Needs three runs", need:"Logged runs per product",
    doc:"06 Kitchen and Production", },
  { id:"warehouse", seat:"Fulfillment and the Warehouse", short:"Warehouse", who:"Owned by the COO", reports:"coo", relationship:true,
    line:"The warehouse ships what customers order, accurately and on time, and the numbers prove it.",
    manages:"A relationship, not a person. The COO owns it. The owner handles anything financial.",
    not:"Customer communication or what gets reordered.",
    measure:"Needs access", need:"Order and inventory accuracy from their system",
    doc:"07 Fulfillment and the Warehouse", },
  { id:"ea", seat:"Executive Assistant", short:"Assistant", who:"Assistant", reports:"founder",
    line:"Take the small work off the owner, then turn it into something that runs without either of you.",
    manages:"The owner's inbox, vendor admin, whatever is being handed over",
    not:"Banking, payments or spend decisions.",
    measure:"Needs build", need:"A simple count of what moved each week",
    doc:"08 Executive Assistant", },
];

// Every metric each seat is held to. Generated from the same spec as the Metrics tracker.
// kind: max (at or under), min (at or over), up (rising), down (flat or falling), yes (1 yes, 0 no)
const METRICS = [
  { seat:"founder", id:"f_dec", name:"Decisions routed through him each week", primary:true, kind:"max", v:5, target:"Under 5", unit:"n", cadence:"Weekly", source:"Decision log"},
  { seat:"founder", id:"f_xfer", name:"Functions transferred and holding", primary:false, kind:"up", v:null, target:"Rising", unit:"n", cadence:"Monthly", source:"Transfer log"},
  { seat:"founder", id:"f_growth", name:"Share of week on growth", primary:false, kind:"up", v:null, target:"Rising from 10%", unit:"pct", cadence:"Monthly", source:"Self report"},
  { seat:"coo", id:"c_dec", name:"Operational decisions closed without the owner", primary:true, kind:"up", v:null, target:"Rising. Baseline at 30 days", unit:"n", cadence:"Weekly", source:"Decision log"},
  { seat:"coo", id:"c_lead", name:"Products under lead time", primary:false, kind:"max", v:0, target:"Zero", unit:"n", cadence:"Weekly", source:"Inventory system"},
  { seat:"coo", id:"c_reorder", name:"Reorders placed inside lead time", primary:false, kind:"min", v:100, target:"100%", unit:"pct", cadence:"Monthly", source:"Purchase log"},
  { seat:"coo", id:"c_late", name:"Liabilities paid late", primary:false, kind:"max", v:0, target:"Zero", unit:"n", cadence:"Monthly", source:"Accounting"},
  { seat:"content", id:"b_rev", name:"Revenue from organic social", primary:true, kind:"up", v:null, target:"Profitable", unit:"usd", cadence:"Monthly", source:"Attribution, once rebuilt"},
  { seat:"content", id:"b_review", name:"Published without brand review", primary:false, kind:"max", v:0, target:"Zero", unit:"n", cadence:"Weekly", source:"Publishing log"},
  { seat:"content", id:"b_mismatch", name:"Site and email mismatches", primary:false, kind:"max", v:0, target:"Zero", unit:"n", cadence:"Monthly", source:"Incident note"},
  { seat:"content", id:"b_va", name:"Creator VA system documented", primary:false, kind:"yes", v:1, target:"Yes", unit:"yes", cadence:"Monthly", source:"The document"},
  { seat:"dev", id:"d_road", name:"Roadmap items shipped each week", primary:true, kind:"up", v:null, target:"Per roadmap", unit:"n", cadence:"Weekly", source:"Roadmap"},
  { seat:"dev", id:"d_bugs", name:"Customer-blocking bugs open over a day", primary:false, kind:"max", v:0, target:"Zero", unit:"n", cadence:"Daily", source:"Issue list"},
  { seat:"dev", id:"d_handover", name:"Handover document current", primary:false, kind:"yes", v:1, target:"Yes", unit:"yes", cadence:"Monthly", source:"The document"},
  { seat:"support", id:"s_resolve", name:"Time to resolve, median hours", primary:true, kind:"max", v:24, target:"Under 24 hours", unit:"h", cadence:"Weekly", source:"Support tool"},
  { seat:"support", id:"s_reply", name:"Time to first reply, median hours", primary:false, kind:"max", v:24, target:"Under 1 business day, scored at 24 hours", unit:"h", cadence:"Weekly", source:"Support tool"},
  { seat:"support", id:"s_open", name:"Issues open past a day", primary:false, kind:"max", v:0, target:"Zero", unit:"n", cadence:"Daily", source:"Support tool"},
  { seat:"support", id:"s_repeat", name:"Repeat questions turned into written answers", primary:false, kind:"up", v:null, target:"Rising", unit:"n", cadence:"Monthly", source:"Site content"},
  { seat:"wholesale", id:"w_out", name:"Outbound activity per day", primary:true, kind:"min", v:10, target:"10 or more a day", unit:"n", cadence:"Daily", source:"Activity log"},
  { seat:"wholesale", id:"w_inbound", name:"Inbound answered same day", primary:false, kind:"min", v:100, target:"100%", unit:"pct", cadence:"Weekly", source:"Inbox"},
  { seat:"wholesale", id:"w_opened", name:"Accounts opened", primary:false, kind:"up", v:null, target:"Rising", unit:"n", cadence:"Monthly", source:"Order records"},
  { seat:"wholesale", id:"w_reorder", name:"Accounts reordering on pattern", primary:false, kind:"up", v:null, target:"Rising", unit:"pct", cadence:"Monthly", source:"Order records"},
  { seat:"kitchen", id:"k_output", name:"Output per dollar", primary:true, kind:"up", v:null, target:"Measured, then rising", unit:"rate", cadence:"Per run", source:"Run log"},
  { seat:"kitchen", id:"k_logged", name:"Runs logged with all three fields", primary:false, kind:"min", v:100, target:"100%", unit:"pct", cadence:"Monthly", source:"Run log"},
  { seat:"kitchen", id:"k_sched", name:"Runs completed on schedule", primary:false, kind:"min", v:100, target:"100%", unit:"pct", cadence:"Monthly", source:"Production schedule"},
  { seat:"kitchen", id:"k_costed", name:"Products with a measured cost", primary:false, kind:"min", v:10, target:"All 10", unit:"n", cadence:"Monthly", source:"Run log"},
  { seat:"warehouse", id:"h_order", name:"Order accuracy", primary:true, kind:"min", v:99.5, target:"99.5% or better", unit:"pct", cadence:"Monthly", source:"Warehouse system"},
  { seat:"warehouse", id:"h_inv", name:"Inventory accuracy", primary:false, kind:"min", v:98, target:"98 to 99%", unit:"pct", cadence:"Monthly", source:"Warehouse system"},
  { seat:"warehouse", id:"h_freight", name:"Freight as a share of revenue", primary:false, kind:"down", v:null, target:"Flat or falling", unit:"pct", cadence:"Monthly", source:"Warehouse invoices"},
  { seat:"warehouse", id:"h_unrec", name:"Orders that never reached the platform", primary:false, kind:"max", v:0, target:"Zero", unit:"n", cadence:"Monthly", source:"Reconciliation"},
  { seat:"ea", id:"e_tasks", name:"Tasks taken off the owner each week", primary:true, kind:"up", v:null, target:"Rising", unit:"n", cadence:"Weekly", source:"Transfer log"},
  { seat:"ea", id:"e_doc", name:"Handed-over tasks with a written version", primary:false, kind:"min", v:100, target:"100%", unit:"pct", cadence:"Monthly", source:"Task notes"},
  { seat:"ea", id:"e_cred", name:"Credential list current", primary:false, kind:"yes", v:1, target:"Yes", unit:"yes", cadence:"Monthly", source:"The list"},
];

// Modeled twelve weeks per metric. Gaps are real states: not built yet, or read monthly or per run.
const SAMPLE_LOG = {
  f_dec: [14,14,13,12,12,11,10,9,9,8,7,7],
  f_xfer: [null,null,1,null,null,null,2,null,null,null,3,null],
  f_growth: [null,null,10,null,null,null,14,null,null,null,18,null],
  c_dec: [3,5,6,8,9,11,12,14,15,17,18,20],
  c_lead: [3,3,2,2,3,2,2,1,2,2,2,2],
  c_reorder: [null,null,50,null,null,null,67,null,null,null,75,null],
  c_late: [null,null,1,null,null,null,0,null,null,null,0,null],
  b_rev: [null,null,null,null,null,null,1240,null,null,null,1610,null],
  b_review: [2,1,1,0,1,0,0,1,0,0,1,1],
  b_mismatch: [null,null,1,null,null,null,0,null,null,null,0,null],
  b_va: [null,null,0,null,null,null,0,null,null,null,0,null],
  d_road: [null,null,2,3,1,3,4,3,2,4,3,4],
  d_bugs: [1,0,0,2,0,0,1,0,0,0,0,0],
  d_handover: [null,null,0,null,null,null,0,null,null,null,1,null],
  s_resolve: [null,null,31,28,26,22,20,19,21,18,17,16],
  s_reply: [null,null,20,18,16,15,14,15,14,13,14,14],
  s_open: [null,null,4,3,3,2,2,3,2,2,2,2],
  s_repeat: [null,null,2,null,null,null,4,null,null,null,6,null],
  w_out: [10,9,11,12,8,10,11,12,13,12,14,13],
  w_inbound: [100,100,0,100,100,100,0,100,100,0,100,100],
  w_opened: [null,null,0,null,null,null,1,null,null,null,2,null],
  w_reorder: [null,null,null,null,null,null,50,null,null,null,50,null],
  k_output: [null,0.52,null,0.55,null,0.54,null,0.58,null,0.61,null,0.6],
  k_logged: [null,null,50,null,null,null,67,null,null,null,83,null],
  k_sched: [null,null,100,null,null,null,100,null,null,null,50,null],
  k_costed: [null,null,1,null,null,null,3,null,null,null,3,null],
  h_order: [null,null,null,null,null,null,99.1,null,null,null,99.6,null],
  h_inv: [null,null,null,null,null,null,97.2,null,null,null,98.4,null],
  h_freight: [null,null,null,null,null,null,11.8,null,null,null,11.2,null],
  h_unrec: [null,null,null,null,null,null,9,null,null,null,6,null],
  e_tasks: [4,6,5,7,8,8,9,11,10,12,12,13],
  e_doc: [null,null,50,null,null,null,60,null,null,null,70,null],
  e_cred: [null,null,1,null,null,null,1,null,null,null,1,null],
};

// What moves off the owner, in order, and where each one is in the three-step
// transfer: watch him do it, do it with him watching, do it alone.
const TRANSFERS = [
  { f:"Reordering product",                         stage:"First", to:"COO", step:2 },
  { f:"Tracking every consumable",                  stage:"First", to:"COO", step:1 },
  { f:"Supplier coordination",                      stage:"First", to:"COO", step:1 },
  { f:"Invoicing and paying liabilities",           stage:"Next",  to:"COO", step:0 },
  { f:"Manufacturer runs and their problems",       stage:"Next",  to:"COO", step:0 },
  { f:"Lab testing and what comes back",            stage:"Next",  to:"COO", step:0 },
  { f:"Reorders and wholesale orders with the warehouse", stage:"Next", to:"COO", step:0 },
  { f:"Wholesale inquiries from the site",          stage:"Next",  to:"Wholesale", step:0 },
  { f:"Vendor communication",                       stage:"Held",  to:"Owner, for control", step:null },
];
const TRANSFER_STEPS = ["Not started","Watched him do it","Done with him watching","Done alone, written"];

const OWNER = {
  only:["Move money","Pay the card","Communicate with the payment processors and the broker","Communicate with outside advisors"],
  choice:["Packaging and brand design","Deal structure","Setting up anything new, before it runs"],
  quote:"Nothing really. Everything can be hired for.",
};
